version: '3.1'
services:
  backend:
    build: ./backend
    ports:
      - "5432:5432"
    container_name: database-backend
    volumes:
      - $VOLUME/postgresql/air/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: airdb

  load_balancer:
    image: nginx
    ports:
      - "80:80"
    container_name: nginx-load-balancer

volumes:
  data:
