  - name: DesigniteJava
  # You may pin to the exact commit or the version.
  # uses: DesigniteTools/DJAction@5de0ca090d14125c6057ba4ec74563c1020ca372
  uses: DesigniteTools/DJAction@v1.0.1
  with:
    # Personal access token
    PAT: # optional, default is No PAT provided
    # provide the QScored api
    QSCORED_API_KEY: # optional, default is No qscore provided
    # User name (email) for QScored
    EMAIL: joao167pedro@gmail.com # optional, default is No username provided
    # QScored project name
    PRJ_NAME: # optional, default is ${{ github.event.repository.name }}
    # is code quality results open-source? True/False
    OPEN_SOURCE: False # optional
    # Designite license key - optional
    D_KEY: # optional, default is No key
          
